const express = require('express')
const app = express()
const cors = require('cors')
const pg = require('pg')
const Redis = require('redis')
const bcrypt = require('bcrypt')
const passport = require('passport')
const dotenv = require('dotenv')